-- +goose Up

-- What API v1 needs on top of the first migration. The tables were written in
-- anticipation of these endpoints; four things could not be settled until the
-- endpoints existed, and each is here with the reason it is.

-- --------------------------------------------------------------------------
-- Pairing remembers the machine it produced
-- --------------------------------------------------------------------------

-- A device-code grant hands the token over exactly once. Without somewhere to
-- record that it has been handed over, a client that polls twice would be minted
-- two devices — or, worse, a stolen device code would mint one of its own after
-- the driver's client already had theirs. The column is that record: a poll that
-- finds it set knows the pairing is spent and returns no token.
ALTER TABLE pairings ADD COLUMN device_id bigint REFERENCES devices (id) ON DELETE SET NULL;

-- Who approved it and when, for the audit trail the admin panel writes anyway.
ALTER TABLE pairings ADD COLUMN decided_at timestamptz;
ALTER TABLE pairings ADD COLUMN decided_by text NOT NULL DEFAULT '';

-- A poll is a lookup by device code and nothing else, so the ordering the admin
-- panel wants — oldest pending first — is its own small index rather than a sort
-- over every pairing ever made.
CREATE INDEX pairings_pending_created ON pairings (created_at) WHERE status = 'pending';

-- --------------------------------------------------------------------------
-- Idempotency keys belong to a device
-- --------------------------------------------------------------------------

-- The obvious shape keys this table on the key alone. That is one client short:
-- the keys are generated by clients, so two of them can collide, and a collision
-- on a bare key would replay one driver's stored response to another driver. The
-- key is therefore scoped by the device that presented it, which is the only
-- thing that makes the replay safe to serve.
--
-- Recreating the table rather than altering it is deliberate: it holds nothing
-- but 24-hour replay cache, no endpoint has written to it yet, and a primary key
-- change is clearer stated once than assembled from four ALTERs.
DROP TABLE idempotency_keys;

CREATE TABLE idempotency_keys (
    device_id     bigint      NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    key           text        NOT NULL,
    request_hash  bytea       NOT NULL,
    status        integer     NOT NULL,
    response_body bytea       NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NOT NULL,
    PRIMARY KEY (device_id, key)
);

CREATE INDEX idempotency_keys_expires_at ON idempotency_keys (expires_at);

-- --------------------------------------------------------------------------
-- A summary carries its own best trace
-- --------------------------------------------------------------------------

-- PUT /stints/{id}/summary is a whole-document replace and its best_trace is one
-- of the fields being replaced. It cannot be best_lap_id: the client may send a
-- summary before the lap it names has been uploaded, or after a lap that was
-- never uploaded at all, and a foreign key would refuse the honest answer. The
-- blob is stored the way every other trace is, with its codec version beside it.
ALTER TABLE stint_summaries ADD COLUMN best_trace bytea NOT NULL DEFAULT '';
ALTER TABLE stint_summaries ADD COLUMN best_trace_codec smallint NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE stint_summaries DROP COLUMN IF EXISTS best_trace_codec;
ALTER TABLE stint_summaries DROP COLUMN IF EXISTS best_trace;

DROP TABLE IF EXISTS idempotency_keys;
CREATE TABLE idempotency_keys (
    key           text        PRIMARY KEY,
    request_hash  bytea       NOT NULL,
    status        integer     NOT NULL,
    response_body bytea       NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NOT NULL
);
CREATE INDEX idempotency_keys_expires_at ON idempotency_keys (expires_at);

DROP INDEX IF EXISTS pairings_pending_created;
ALTER TABLE pairings DROP COLUMN IF EXISTS decided_by;
ALTER TABLE pairings DROP COLUMN IF EXISTS decided_at;
ALTER TABLE pairings DROP COLUMN IF EXISTS device_id;
