package db

import (
	"encoding/hex"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// UUIDLen is the length of a UUID in bytes.
const UUIDLen = 16

// ErrBadUUID reports an identifier that is not a UUID. Stint identifiers are
// generated by the client, so this is an ordinary answer to a request rather
// than a fault: the caller turns it into the contract's "invalid".
var ErrBadUUID = errors.New("db: that is not a UUID")

// UUID is the identifier a client generates for a stint. API v1 asks for a
// UUIDv7, which sorts by creation time; this package carries any syntactically
// valid UUID, because refusing a v4 would break a client for no benefit the
// database can name.
type UUID [UUIDLen]byte

// ParseUUID reads the canonical 8-4-4-4-12 spelling, in either case. Braces,
// a "urn:uuid:" prefix and the unhyphenated form are all refused: one spelling
// on the wire means one spelling in a log line and in the admin panel.
func ParseUUID(s string) (UUID, error) {
	var u UUID
	if len(s) != 36 || s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
		return u, fmt.Errorf("%w: %q is not the 8-4-4-4-12 form", ErrBadUUID, s)
	}
	groups := [...][2]int{{0, 8}, {9, 13}, {14, 18}, {19, 23}, {24, 36}}
	at := 0
	for _, g := range groups {
		n, err := hex.Decode(u[at:], []byte(s[g[0]:g[1]]))
		if err != nil {
			return UUID{}, fmt.Errorf("%w: %q holds something that is not a hex digit", ErrBadUUID, s)
		}
		at += n
	}
	return u, nil
}

// String renders the canonical lower-case spelling.
func (u UUID) String() string {
	var b [36]byte
	hex.Encode(b[0:8], u[0:4])
	b[8] = '-'
	hex.Encode(b[9:13], u[4:6])
	b[13] = '-'
	hex.Encode(b[14:18], u[6:8])
	b[18] = '-'
	hex.Encode(b[19:23], u[8:10])
	b[23] = '-'
	hex.Encode(b[24:36], u[10:16])
	return string(b[:])
}

// Version is the UUID's version nibble: 7 for the time-ordered identifiers API
// v1 asks clients to generate, 4 for a random one.
func (u UUID) Version() int { return int(u[6] >> 4) }

func (u UUID) pg() pgtype.UUID { return pgtype.UUID{Bytes: u, Valid: true} }

func uuidFromPg(v pgtype.UUID) UUID { return UUID(v.Bytes) }
